name: Create DynamoDB Table

on:
  workflow_dispatch: # Permite disparo manual

env:
  DYNAMO_NAME: "client_fast_food"
  KEY_NAME: "cpf"

jobs:
  create-dynamodb:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Create DynamoDB Table
      run: |
        aws dynamodb create-table \
          --table-name $DYNAMO_NAME \
          --attribute-definitions AttributeName=$KEY_NAME,AttributeType=S \
          --key-schema AttributeName=$KEY_NAME,KeyType=HASH \
          --billing-mode PAY_PER_REQUEST

    - name: Confirm Table Creation
      run: aws dynamodb describe-table --table-name $DYNAMO_NAME
